(in-package :pvs)

(defun typecheck-let-bindings* (bindings arg anum &optional substs)
  (when bindings
    (let* ((bd (car bindings))
	   (dtype (get-let-binding-type bd bindings arg anum))
	   (type (substit (if (typep dtype 'dep-binding)
			      (type dtype)
			      dtype)
		   substs)))
      (setf (type bd) type)
      (unless (fully-instantiated? type)
	(type-error (car bindings)
	  "Could not determine the full theory instance"))
      (let ((*bound-variables* (cons bd *bound-variables*)))
	(typecheck-let-bindings* (cdr bindings) arg (1+ anum)
				 (if (typep dtype 'dep-binding)
				     (acons dtype bd substs)
				     substs))))))
